config/routes.rb
Rails.application.routes.draw do
  root 'departments#index'
  resources :departments do 
    resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  # before_action :set_department, only: [:show, :edit, :update, :destroy]
  def index
    @departments = Department.all
  end

  def show
  end

  def new
    @department = Department.new
    render partial: "form"
  end

  def create 
    @department = Department.new(department_params)
    if @department.save
      redirect_to departments_path
    else
      render partial: :new
    end
  end
  def update 
    @department = Department.new(department_params)
    if @department.save
      redirect_to departments_path
    else
      render partial: "form" 
    end
  end


  def edit
    render partial: "form"
  end

  def update
    if @department.update(department_params)
      redirect_to @department
    else
      render :edit
    end
  end

  def destroy 
    @department.destroy
    redirect_to departments_path
  else 
    render :department_path
  end

 

  private
  # def set_department 
  #   @department = Department.find(params[:id])
  # end

  def department_params
    params.require(:department).permit(:name)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department 
  before_action :set_item, only: [:show, edit,]

  def index
    @departments = Department.items
  end

  def show
  end

  def new
    @item = @department.item.new
  end

  def create
    @item = @department.item.new(params[:id])
    if @item.create
      redirect_to [@department, @item]
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item = @department.item(item_params)
      redirect_to [@department, @item]
    else
      render :edit
   end
  end

  def destrooy
    @item = @department.item.destroy 
    redirect departments_items_path
  end



  private

  def set_department 
    @department = Department.find(params[:id])
 end

 def set_item
  @item = @department.item.find(parmas[:id]) 
end

def item_params
  params.require(:name).permit
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departments/_form.html.erb
<h1><%= @department.id ? "Edit Department" : "Create Department" %></h1>
<hr />
<%= form_for @department do |f| %>
    <%= f.label :name required: true %>
    <%= f.text_field :name %>
    
    <%= f.submit %>
    <% end %>

app/views/departments/edit.html.erb
<h1>Departments#edit</h1>
<p>Find me in app/views/departments/edit.html.erb</p>

app/views/departments/index.html.erb
<h1>Departments Store</h1>
<br />
<%= link_to "Add a new Department", new_department_path %>
<% @departments.each do |department| %>
    <h2><%= department.name %></h2>
    <p> <%=link_to "Show Department", department_path(department)%></p>
    <p> <%=link_to "Edit", edit_department_path(department)%></p>
<% end %>

app/views/departments/new.html.erb
<h1>Departments#new</h1>
<p> <p> <%=link_to "Edit", edit_department_path(department)%></p></p>

app/views/departments/show.html.erb
<h1>Department</h1>
<br />
<p>Name:<% @department.name %></p>
<p>Items:<% @department.item%></p>
<br />
<br />
<%= link_to "Edit Department", edit_department_path %>
<%= link_to "Delete Department", department_path(@department), method: :delete %>
<%= link_to "Back", departments_path %>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/navbar.html.erb
<%= link_to "Home" departments_path %>